[project]
name = "newclid-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Simeon Vutov", email = "s.vutov@student.tudelft.nl" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.136.1",
    "redis>=7.4.0",
    "rq>=2.8.0",
    "uvicorn>=0.35.0",
    "newclid[yuclid]",
    "py-yuclid",
]

[project.optional-dependencies]
test = [
    "pytest>=9.0.0",
    "httpx>=0.28.0",
]

[project.scripts]
newclid-backend = "newclid_backend:main"

[build-system]
requires = ["uv_build>=0.11.13,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
newclid = { git = "https://github.com/SimeonVutov/Newclid", subdirectory = "newclid", rev = "c0b15e791dab78e89bf8dbe0dc9a31fbb9297393" }
py-yuclid = { git = "https://github.com/SimeonVutov/Newclid", subdirectory = "yuclid", rev = "c0b15e791dab78e89bf8dbe0dc9a31fbb9297393" }
